# Generated by Django 5.0 on 2024-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Front-End', 'Front-End')], max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('salary', models.IntegerField()),
                ('hr_user', models.CharField(max_length=50)),
            ],
        ),
    ]
